"""Initial Migration

Revision ID: b06119cd036a
Revises: 18546b2b440d
Create Date: 2020-11-02 22:31:30.960122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b06119cd036a'
down_revision = '18546b2b440d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('posted_date', sa.DateTime(), nullable=True))
    op.add_column('comments', sa.Column('posted_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'posted_date')
    op.drop_column('blogs', 'posted_date')
    # ### end Alembic commands ###
